"""
Generate dialogueCatalog.ts from bollywood_200_dialogues.json and hollywood_200_dialogues.json.
"""

import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data')
OUT_FILE = os.path.join(
    os.path.dirname(__file__), '..', 'guess-the-frame-colyseus', 'src', 'data', 'dialogueCatalog.ts'
)

BOLLYWOOD_FILE = os.path.join(DATA_DIR, 'bollywood_200_dialogues.json')
HOLLYWOOD_FILE = os.path.join(DATA_DIR, 'hollywood_200_dialogues.json')


def escape_ts_string(s: str) -> str:
    """Escape a string for use inside a TypeScript single-quoted string literal."""
    s = s.replace('\\', '\\\\')
    s = s.replace("'", "\\'")
    s = s.replace('\n', '\\n')
    s = s.replace('\r', '')
    return s


def build_entry(item: dict, region: str) -> str:
    """Build a single TypeScript object literal string for one catalogue entry."""
    eid = item['id']
    dialogue = escape_ts_string(item['dialogue'])
    answer = item['answer']  # already uppercase in JSON
    year = item.get('year', '')
    character = escape_ts_string(item.get('character', ''))
    actor = escape_ts_string(item.get('actor', ''))
    tag = item.get('tag', '')

    lines = [
        '  {',
        f"    id: '{eid}',",
        "    category: 'dialogue',",
        "    type: 'dialogue',",
        f"    content: '{dialogue}',",
        f"    dialogue: '{dialogue}',",
        f"    answer: '{escape_ts_string(answer)}',",
    ]

    # Fight Club special rule
    if answer == 'FIGHT CLUB':
        lines.append("    displayAnswer: '***** ****',")

    if year:
        lines.append(f"    year: '{escape_ts_string(year)}',")
    if character:
        lines.append(f"    character: '{character}',")
    if actor:
        lines.append(f"    actor: '{actor}',")

    lines.append(f"    region: '{region}',")

    if tag:
        lines.append(f"    tag: '{escape_ts_string(tag)}',")

    lines.append('  }')
    return '\n'.join(lines)


def main():
    with open(BOLLYWOOD_FILE, 'r', encoding='utf-8') as f:
        bollywood = json.load(f)
    with open(HOLLYWOOD_FILE, 'r', encoding='utf-8') as f:
        hollywood = json.load(f)

    print(f'Loaded {len(bollywood)} Bollywood dialogues')
    print(f'Loaded {len(hollywood)} Hollywood dialogues')

    entries: list[str] = []

    for item in bollywood:
        entries.append(build_entry(item, 'bollywood'))

    for item in hollywood:
        entries.append(build_entry(item, 'hollywood'))

    ts_content = (
        "// Auto-generated by scripts/generate_dialogue_catalog.py — DO NOT EDIT\n\n"
        "export interface DialogueCatalogItem {\n"
        "  id: string;\n"
        "  category: 'dialogue';\n"
        "  type: 'dialogue';\n"
        "  content: string;\n"
        "  dialogue: string;\n"
        "  answer: string;\n"
        "  displayAnswer?: string;\n"
        "  year?: string;\n"
        "  character?: string;\n"
        "  actor?: string;\n"
        "  region?: 'bollywood' | 'hollywood';\n"
        "  tag?: 'new' | 'classic';\n"
        "  aliases?: string[];\n"
        "}\n\n"
        "export const DIALOGUE_CATALOG: DialogueCatalogItem[] = [\n"
        + ',\n'.join(entries) + ',\n'
        + '];\n'
    )

    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
    with open(OUT_FILE, 'w', encoding='utf-8') as f:
        f.write(ts_content)

    print(f'Generated {len(entries)} entries → {os.path.abspath(OUT_FILE)}')


if __name__ == '__main__':
    main()
